### ISSUE TITLE
Separate Left and Right VaneVerticalDirection?

### ISSUE THREAD

**Issue by espenjohannessen** [Black-Thunder/ioBroker.melcloud#24]
I see that you've added a vaneHorizontalDirection value for separate control of the left and right vanes a few versions back, but I don't see a similar option for the vertical vanes (one up and one down). Do you know if this is something that is supported in MelCloud, and if so, exactly how it works? The use case is as follows:

I have a Kaiteki 6600 mounted in between two floors, in the stairway, and use the two separate vertical vanes to direct air both up and down. When the temperature on the main floor is above 21 degrees I would like the hot airstream to be split between the two floors (left vane up, right vane down), but when the temperature on the main floor drops below 21 degrees I would like the hot airstream to only be pushed into the main floor (both vanes up) to heat it up as quickly as possible.

**Comment by espenjohannessen** [comment]
![image](https://user-images.githubusercontent.com/3808959/100024875-ee154a00-2de7-11eb-9367-1c14e74aa141.png)

**Comment by Black-Thunder** [comment]
I don't really know if there are models out there, which horizontal vanes can be controlled independently or set to 50/50 (up/down) like the horizonal vanes on some models. Are you able to do so through the MELCloud app or your remote control?

If yes, please change the log level of the adapter to "silly", set the horizontal vanes to your desired position and post the log file here. Maybe the settings for the vertical vanes can be extended then.
If you can't set it through the app or remote control, then it's not possible. Generally speaking the adapter just mimics the mechanisms used in the app, so it can't provide more functionality than the app itself.

**Comment by espenjohannessen** [comment]
Yeah, on the Kaiteki models this can be done using the remote - as shown in the picture above (Left - Vane - Right) - but I'm not able to do the same through the MelCloud app. Here there is only one vertical vane setting and it seems to show the status of the left vane and set both left and right when changed.

I did kinda assume the same is true for the API, but was hoping to be proven wrong : )

I'm not sure how to do the logging you suggested, but I've been observing the VaneVerticalDirection and VaneHorizontalDirection in the ListDevices endpoint directly to verify my assumptions.

**Comment by Black-Thunder** [comment]
In the admin panel go to "Instances", switch to expert mode (if not already), find the melcloud-adapter in the list and change the log level there from "info" to "silly".

![Untitled](https://user-images.githubusercontent.com/972581/100063313-53415d80-2e31-11eb-9d3b-42eb07662719.png)

Then use your remote to set the vanes, wait 1-2 minutes for the cloud to update the values and then attach the complete logfile please (via "Log" tab -> "Download log"). Makes sure to remove your MELCloud credentials there before posting!
If the API supports this settings, it should be visible in the logfile.

Afterwards you should change the logging back to "info", otherwise you logfile will be flooded with entries. 😉

**Comment by Black-Thunder** [comment]
As this feature can't be set through the app apparently and there was no more feedback, I'll close this issue. Feel free to reopen if needed.
